vip @jumpcrew.preprod -- wp post term add 286497 business-category local-services --url=content-preprod.mybaseguide.com && vip @jumpcrew.preprod -- wp post term remove % business-category mm --url=content-preprod.mybaseguide.com
vip @jumpcrew.preprod -- wp post term add 286492 business-category local-services --url=content-preprod.mybaseguide.com && vip @jumpcrew.preprod -- wp post term remove % business-category mm --url=content-preprod.mybaseguide.com
vip @jumpcrew.preprod -- wp post term add 146282 business-category local-services --url=content-preprod.mybaseguide.com && vip @jumpcrew.preprod -- wp post term remove % business-category mm --url=content-preprod.mybaseguide.com
vip @jumpcrew.preprod -- wp post term add 144853 business-category local-services --url=content-preprod.mybaseguide.com && vip @jumpcrew.preprod -- wp post term remove % business-category mm --url=content-preprod.mybaseguide.com
vip @jumpcrew.preprod -- wp post term add 25047 business-category local-services --url=content-preprod.mybaseguide.com && vip @jumpcrew.preprod -- wp post term remove 25047 business-category mm --url=content-preprod.mybaseguide.com
vip @jumpcrew.preprod -- wp post term add  business-category local-services --url=content-preprod.mybaseguide.com && vip @jumpcrew.preprod -- wp post term remove  business-category mm --url=content-preprod.mybaseguide.com
vip @jumpcrew.preprod -- wp post term add % business-category local-services --url=content-preprod.mybaseguide.com && vip @jumpcrew.preprod -- wp post term remove % business-category mm --url=content-preprod.mybaseguide.com
vip @jumpcrew.preprod -- wp post term add % business-category local-services --url=content-preprod.mybaseguide.com && vip @jumpcrew.preprod -- wp post term remove % business-category mm --url=content-preprod.mybaseguide.com
vip @jumpcrew.preprod -- wp post term add % business-category local-services --url=content-preprod.mybaseguide.com && vip @jumpcrew.preprod -- wp post term remove % business-category mm --url=content-preprod.mybaseguide.com
vip @jumpcrew.preprod -- wp post term add % business-category local-services --url=content-preprod.mybaseguide.com && vip @jumpcrew.preprod -- wp post term remove % business-category mm --url=content-preprod.mybaseguide.com
vip @jumpcrew.preprod -- wp post term add % business-category local-services --url=content-preprod.mybaseguide.com && vip @jumpcrew.preprod -- wp post term remove % business-category mm --url=content-preprod.mybaseguide.com
vip @jumpcrew.preprod -- wp post term add % business-category local-services --url=content-preprod.mybaseguide.com && vip @jumpcrew.preprod -- wp post term remove % business-category mm --url=content-preprod.mybaseguide.com
vip @jumpcrew.preprod -- wp post term add % business-category local-services --url=content-preprod.mybaseguide.com && vip @jumpcrew.preprod -- wp post term remove % business-category mm --url=content-preprod.mybaseguide.com
vip @jumpcrew.preprod -- wp post term add % business-category local-services --url=content-preprod.mybaseguide.com && vip @jumpcrew.preprod -- wp post term remove % business-category mm --url=content-preprod.mybaseguide.com
vip @jumpcrew.preprod -- wp post term add % business-category local-services --url=content-preprod.mybaseguide.com && vip @jumpcrew.preprod -- wp post term remove % business-category mm --url=content-preprod.mybaseguide.com
vip @jumpcrew.preprod -- wp post term add % business-category local-services --url=content-preprod.mybaseguide.com && vip @jumpcrew.preprod -- wp post term remove % business-category mm --url=content-preprod.mybaseguide.com
vip @jumpcrew.preprod -- wp post term add } business-category local-services --url=content-preprod.mybaseguide.com && vip @jumpcrew.preprod -- wp post term remove } business-category mm --url=content-preprod.mybaseguide.com
vip @jumpcrew.preprod -- wp post term add % business-category local-services --url=content-preprod.mybaseguide.com && vip @jumpcrew.preprod -- wp post term remove % business-category mm --url=content-preprod.mybaseguide.com
vip @jumpcrew.preprod -- wp post term add 286497 business-category local-services --url=content-preprod.mybaseguide.com && vip @jumpcrew.preprod -- wp post term remove % business-category mm --url=content-preprod.mybaseguide.com
vip @jumpcrew.preprod -- wp post term add 286492 business-category local-services --url=content-preprod.mybaseguide.com && vip @jumpcrew.preprod -- wp post term remove % business-category mm --url=content-preprod.mybaseguide.com
vip @jumpcrew.preprod -- wp post term add 146282 business-category local-services --url=content-preprod.mybaseguide.com && vip @jumpcrew.preprod -- wp post term remove % business-category mm --url=content-preprod.mybaseguide.com
vip @jumpcrew.preprod -- wp post term add 144853 business-category local-services --url=content-preprod.mybaseguide.com && vip @jumpcrew.preprod -- wp post term remove % business-category mm --url=content-preprod.mybaseguide.com
vip @jumpcrew.preprod -- wp post term add 25047 business-category local-services --url=content-preprod.mybaseguide.com && vip @jumpcrew.preprod -- wp post term remove 25047 business-category mm --url=content-preprod.mybaseguide.com
vip @jumpcrew.preprod -- wp post term add  business-category local-services --url=content-preprod.mybaseguide.com && vip @jumpcrew.preprod -- wp post term remove  business-category mm --url=content-preprod.mybaseguide.com
vip @jumpcrew.preprod -- wp post term add 286497 business-category local-services --url=content-preprod.mybaseguide.com && vip @jumpcrew.preprod -- wp post term remove % business-category mm --url=content-preprod.mybaseguide.com
vip @jumpcrew.preprod -- wp post term add 286492 business-category local-services --url=content-preprod.mybaseguide.com && vip @jumpcrew.preprod -- wp post term remove % business-category mm --url=content-preprod.mybaseguide.com
vip @jumpcrew.preprod -- wp post term add 146282 business-category local-services --url=content-preprod.mybaseguide.com && vip @jumpcrew.preprod -- wp post term remove % business-category mm --url=content-preprod.mybaseguide.com
vip @jumpcrew.preprod -- wp post term add 144853 business-category local-services --url=content-preprod.mybaseguide.com && vip @jumpcrew.preprod -- wp post term remove % business-category mm --url=content-preprod.mybaseguide.com
vip @jumpcrew.preprod -- wp post term add 25047 business-category local-services --url=content-preprod.mybaseguide.com && vip @jumpcrew.preprod -- wp post term remove 25047 business-category mm --url=content-preprod.mybaseguide.com
vip @jumpcrew.preprod -- wp post term add  business-category local-services --url=content-preprod.mybaseguide.com && vip @jumpcrew.preprod -- wp post term remove  business-category mm --url=content-preprod.mybaseguide.com
